### ISSUE TITLE
js part not working

### ISSUE THREAD

**Issue by SouravBasak08** [SouravFlamingosTech/calender#3]
I'm trying to set up Google calendar API on Node, using the Node.js quick start that appear [here](https://developers.google.com/google-apps/calendar/quickstart/nodejs)

After following all the first 3 steps and running my quickstart.js to check if it works (which i copied and pasted from the quickstart) , i get the following error:

"TypeError: googlAuth is not a constructor" it refer to this line of code :

  var auth = new googleAuth();
googleAuth is declared like that:

var googleAuth = require('google-auth-library');

**Comment by Manavpreeet** [comment]
I would like to work on it
